### ISSUE TITLE
panic error by import turbodbc lib

### ISSUE THREAD

**Issue by cooljl31** [sbinet/go-python#56]
System info:
MacOs Sierra
10.12.6

Error could not inport turbodbc

```
package main

import (
	"fmt"

	python "github.com/sbinet/go-python"
)

func init() {
	err := python.Initialize()
	if err != nil {
		panic(err.Error())
	}
}

func main() {
	turboExasol := python.PyImport_ImportModule("turbodbc")
	if turboExasol != nil {
		panic("could not inport turbodbc")
	}
	fmt.Printf("%v", turboExasol)
	connection := turboExasol.GetAttrString(`dsn=exasolution-io352fw_64`)
	if connection != nil {
		panic("could not get turbodbc(dsn=exasolution-io352fw_64)")
	}
	fmt.Printf(" %v", connection)
}
```

**Comment by cooljl31** [comment]
I forgot to mention the library correctly install
```
Requirement already satisfied: turbodbc in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pybind11>=2.1.0 in /usr/local/lib/python3.6/site-packages (from turbodbc)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from turbodbc)
```

this python script work
```pyton
from turbodbc import connect

connection = connect(dsn = 'exasolution-io352fw_64')
cursor = connection.cursor()
cursor.execute("SELECT CATEGORY_NAME FROM STATISTICS.WEB_CATEGORY WHERE statistics.web_category.customer_id = 0001")

for row in cursor:
    print(row)
```

**Comment by sbinet** [comment]
`PyImport_ImportMode` returns a `PyObject*`:
https://docs.python.org/2/c-api/import.html#c.PyImport_ImportModule

so the test:
```go
	if turboExasol != nil {
		panic("could not inport turbodbc")
	}
```

should really read:
```go
	if turboExasol == nil {
		panic("could not inport turbodbc")
	}
```

that said, do note that `sbinet/go-python` only supports Python-2, and it seems `turbodbc` is picked up from a `python3.6` install (and has thus been, presumably, compiled against Python-3).

**Comment by cooljl31** [comment]
i have the same error on Python-2.7
![screen shot 2017-09-14 at 9 53 14 pm](https://user-images.githubusercontent.com/6700684/30452798-2ed3aaf2-9997-11e7-820d-1cc46cb68730.png)

**Comment by sbinet** [comment]
ok.
but... did you notice that `PyImport_ImportModule` returns the module so you should write:

```go
if turboExasol == nil {
	panic("could not inport turbodbc")
}
```

_ie:_ your if condition should be reversed.

**Comment by sivakon** [comment]
```
func complicatedPythonCode() {
	python.Initialize()

	someModule := python.PyImport_ImportModule("pandas")
	if someModule == nil {
		panic("Error importing pandas")
	}
	python.Finalize()

}
```
Gives me the error:

```
panic: Error importing pandas

goroutine 1 [running]:
main.complicatedPythonCode()
        /Users/sivaram.konanki/Documents/go-python/comp.go:10 +0x6e
main.main()
        /Users/sivaram.konanki/Documents/go-python/main.go:13 +0x62
```

**Comment by sbinet** [comment]
Closing of old age.
